MeetHub/MeetHub/Models/Groupe.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;

namespace MeetHub.Models
{
    public class Groupe
    {
        [Key]
        public int GroupeId { get; set; }
        [Required]
        public string Nom { get; set; }
        [Required]
        public string Lieu { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime DateCreation { get; set; }
        public ICollection<ApplicationUser> Membres { get; set; }
        public ICollection<Evenement> Evenements { get; set; }
        public ApplicationUser Createur { get; set; }

        public Groupe()
        {
            this.DateCreation = new DateTime();
            this.Membres = new List<ApplicationUser>();
        }

        public Groupe(string nom, string lieu, string description, ApplicationUser createur)
        {
            this.Nom = nom;
            this.Lieu = lieu;
            this.Description = description;
            this.DateCreation = DateTime.Now;
            this.Membres = new List<ApplicationUser>();
            this.Evenements = new List<Evenement>();
            this.Createur = createur;
        }
    }
}

MeetHub/MeetHub/ViewModels/GroupeViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MeetHub.Models
{
    public class GroupeViewModel
    {
        public int GroupeId { get; set; }
        public string Nom { get; set; }
        public string Lieu { get; set; }
        public string Description { get; set; }
        public string DateCreation { get; set; }
        public string NbMembres { get; set; }
        public string NbEvenements { get; set; }
        public ApplicationUser Createur { get; set; }
    }

    public class GroupeGlobalViewModel
    {
        [Required]
        [Display(Name = "Nom")]
        public string AjouterNom { get; set; }

        [Required]
        [Display(Name = "Quartier général")]
        public string AjouterLieu { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string AjouterDescription { get; set; }

        public List<GroupeViewModel> groupes { get; set; }
        public List<GroupeViewModel> invitations { get; set; }
        public List<GroupeViewModel> groupesrecents { get; set; }

        public GroupeGlobalViewModel()
        {
            this.groupes = new List<GroupeViewModel>();
            this.invitations = new List<GroupeViewModel>();
            this.groupesrecents = new List<GroupeViewModel>();
        }
    }
}

MeetHub/MeetHub/Controllers/GroupeController.cs
using MeetHub.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MeetHub.Controllers
{
    public class GroupeController : Controller
    {
        public ActionResult AfficherGroupes()
        {
            using (var context = new ApplicationDbContext())
            {

                var UserId = User.Identity.GetUserId();
                var ListeMesGroupes = context.Groupes
                    .Where(groupe => UserId == groupe.Createur.Id)
                    .Select(groupe => new
                    {
                        GroupeId = groupe.GroupeId,
                        Nom = groupe.Nom,
                        Lieu = groupe.Lieu,
                        Description = groupe.Description,
                        DateCreation = groupe.DateCreation,
                        Membres = groupe.Membres,
                        Evenements = groupe.Evenements,
                        Createur = groupe.Createur
                    });

                var ListeInvitationsGroupes = context.Groupes
                    .Where(groupe =>  groupe.Membres.Any(membre => membre.Id == UserId))
                    .Select(groupe => new
                    {
                        GroupeId = groupe.GroupeId,
                        Nom = groupe.Nom,
                        Lieu = groupe.Lieu,
                        Description = groupe.Description,
                        DateCreation = groupe.DateCreation,
                        Membres = groupe.Membres,
                        Evenements = groupe.Evenements,
                        Createur = groupe.Createur
                    });

                var ListeGroupesRecents = context.Groupes
                    .Where(groupe => !groupe.Membres.Any(membre => membre.Id == UserId))
                    .Take(6)
                    .Select(groupe => new
                    {
                        GroupeId = groupe.GroupeId,
                        Nom = groupe.Nom,
                        Lieu = groupe.Lieu,
                        Description = groupe.Description,
                        DateCreation = groupe.DateCreation,
                        Membres = groupe.Membres,
                        Evenements = groupe.Evenements,
                        Createur = groupe.Createur
                    });
            

                ViewBag.Message = "Groupes";
                var viewModel = new GroupeGlobalViewModel();
                foreach(var g in ListeMesGroupes)
                {
                    viewModel.groupes.Add(new GroupeViewModel {
                        GroupeId = g.GroupeId,
                        Nom = g.Nom,
                        Lieu = g.Lieu,
                        Description = g.Description,
                        DateCreation = g.DateCreation.Date.ToString("D"),
                        NbMembres = g.Membres.Count().ToString(),
                        NbEvenements = g.Evenements.Count().ToString(),
                        Createur = g.Createur
                    });
                }

                foreach (var g in ListeInvitationsGroupes)
                {
                    viewModel.invitations.Add(new GroupeViewModel
                    {
                        GroupeId = g.GroupeId,
                        Nom = g.Nom,
                        Lieu = g.Lieu,
                        Description = g.Description,
                        DateCreation = g.DateCreation.Date.ToString("D"),
                        NbMembres = g.Membres.Count().ToString(),
                        NbEvenements = g.Evenements.Count().ToString(),
                        Createur = g.Createur
                    });
                }

                foreach (var g in ListeGroupesRecents)
                {
                    viewModel.groupesrecents.Add(new GroupeViewModel
                    {
                        GroupeId = g.GroupeId,
                        Nom = g.Nom,
                        Lieu = g.Lieu,
                        Description = g.Description,
                        DateCreation = g.DateCreation.Date.ToString("D"),
                        NbMembres = g.Membres.Count().ToString(),
                        NbEvenements = g.Evenements.Count().ToString(),
                        Createur = g.Createur
                    });
                }

                return View(viewModel);
            }
        }

        // POST: /Groupe/AjouterGroupe
        [HttpPost]
        [AllowAnonymous]
        public ActionResult AjouterGroupe(GroupeGlobalViewModel model)
        {
            using (var context = new ApplicationDbContext())
            {
                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);
                var groupe = new Groupe(model.AjouterNom, model.AjouterLieu, model.AjouterDescription, Createur);
                groupe.Membres.Add(Createur);
                context.Groupes.Add(groupe);
                context.SaveChanges();
                return RedirectToAction("AfficherGroupes");
            }
        }

        public ActionResult SupprimerGroupe(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                var groupe = context.Groupes
                   .FirstOrDefault(g => Id == g.GroupeId);
                context.Groupes.Remove(groupe);
                context.SaveChanges();
                return RedirectToAction("AfficherGroupes");
            }
        }

        public ActionResult RejoindreGroupe(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                //On recupere le groupe
                var groupe = context.Groupes
                    .Include("Membres")
                   .FirstOrDefault(g => Id == g.GroupeId);
                //On recupere l'utilisateur courant
                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);

                //On l'ajoute à la liste des membres du groupe
                groupe.Membres.Add(Createur);
                context.SaveChanges();
                return RedirectToAction("AfficherGroupes");
            }
        }

        public ActionResult QuitterGroupe(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                //On recupere le groupe
                var groupe = context.Groupes
                    .Include("Membres")
                   .FirstOrDefault(g => Id == g.GroupeId);
                //On recupere l'utilisateur courant
                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);

                //On le retire à la liste des membres du groupe
                groupe.Membres.Remove(Createur);
                context.SaveChanges();
                return RedirectToAction("AfficherGroupes");
            }
        }
    }
}

MeetHub/MeetHub/Views/Groupe/AfficherGroupes.cshtml
@model MeetHub.Models.GroupeGlobalViewModel
@{
    ViewBag.Title = "Groupes";
}
<hr />
<div class="col-sm-12 container ">
    <div class="submain col-sm-6 col-sm-offset-3">
        @using (Html.BeginForm("AjouterGroupe", "Groupe", FormMethod.Post, new { @class = "ui form", role = "form" }))
        {
            <h4>Ajouter un nouveau groupe</h4>
            <hr />
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterNom, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextBoxFor(m => m.AjouterNom)
                </div>
            </div>
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterLieu, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextBoxFor(m => m.AjouterLieu)
                </div>
            </div>
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterDescription, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextAreaFor(m => m.AjouterDescription)
                </div>
            </div>
            <div class="field">
                <div class="text-center">
                    <input type="submit" class="ui button waves-effect waves-green" value="Ajouter" />
                </div>
            </div>
        }
    </div>
</div>

<div class="col-sm-12 container">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200"> Mes Groupes </h4>
    <br />
    <div class="row">
        @foreach (var groupe in Model.groupes)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big text-uppercase">@groupe.Nom</a>
                    <hr />
                    <p>Crée le @groupe.DateCreation</p>
                    <p>Quartier général : @groupe.Lieu</p>
                    <p>Description: @groupe.Description</p>
                    <center>
                        <div class="ui buttons">
                            <button class="ui positive button">MODIFIER</button>
                            <div class="or" data-text="ou"></div>
                            @Html.ActionLink("SUPPRIMER", "SupprimerGroupe", new { Id = @groupe.GroupeId } , new { @class = "ui negative button" })
                        </div>
                    </center>
                </div>
            </div>
        }
    </div>
</div>
<hr>
<div class="col-sm-12 container">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200">Participations</h4>
    <br/>
    <div class="row">
        @foreach (var groupe in Model.invitations)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big text-uppercase">@groupe.Nom</a>
                    <hr />
                    <p>Crée le @groupe.DateCreation</p>
                    <p>Quartier général : @groupe.Lieu</p>
                    <p>Createur : @groupe.Createur.Email</p>
                    <p>Description: @groupe.Description</p>
                    <div class="ui mini teal message">
                        <p>Nous sommes une communauté de @groupe.NbMembres membre(s)</p>
                    </div>
                    <div class="ui mini teal message">
                        <p>Nous avons organise(s) @groupe.NbEvenements évènements</p>
                    </div>
                    <center>
                        @Html.ActionLink("QUITTER", "QuitterGroupe", new { Id = @groupe.GroupeId }, new { @class = "ui red button" })
                    </center>
                </div>
            </div>
        }
    </div>
</div>
<hr>
<div class="container col-sm-12">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200">Nouveaux groupes</h4>
    <br />
    <div class="row">
        @foreach (var groupe in Model.groupesrecents)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big text-uppercase">@groupe.Nom</a>
                    <hr />
                    <p>Crée le @groupe.DateCreation</p>
                    <p>Quartier général : @groupe.Lieu</p>
                    <p>Createur : @groupe.Createur.Email</p>
                    <p>Description: @groupe.Description</p>
                    <div class="ui mini teal message">
                        <p>Nous sommes une communauté de @groupe.NbMembres membre(s)</p>
                    </div>
                    <div class="ui mini teal message">
                        <p>Nous avons organise(s) @groupe.NbEvenements évènements</p>
                    </div>
                    <center>
                        @Html.ActionLink("REJOINDRE", "RejoindreGroupe", new { Id = @groupe.GroupeId }, new { @class = "ui blue button" })
                    </center>
                </div>
            </div>
        }
    </div>
</div>