MeetHub/MeetHub/Models/Evenement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MeetHub.Models
{
    public class Evenement
    {
        [Key]
        public int EvenementId { get; set; }
        [Required]
        public string Nom { get; set; }
        [Required]
        public string Lieu { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
		public string Date{ get; set; }
        public ICollection<ApplicationUser> Membres { get; set; }
        public ApplicationUser Createur { get; set; }

        public Evenement()
        {

        }

        public Evenement(string nom, string lieu, string description, string date, ApplicationUser createur)
        {
            this.Nom = nom;
            this.Lieu = lieu;
            this.Description = description;
            this.Date = date;
            this.Membres = new List<ApplicationUser>();
            this.Createur = createur;
        }
    }

}

MeetHub/MeetHub/ViewModels/EvenementViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MeetHub.Models
{
    public class EvenementViewModel
    {
        public int EvenementId { get; set; }
        public string Nom { get; set; }
        public string Lieu { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string NbMembres { get; set; }
        public Groupe Groupe { get; set; }
        public ApplicationUser Createur { get; set; }
    }

    public class EvenementGlobalViewModel
    {
        [Required]
        [Display(Name = "Nom")]
        public string AjouterNom { get; set; }

        [Required]
        [Display(Name = "Quartier général")]
        public string AjouterLieu { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string AjouterDescription { get; set; }

        [Required]
        [Display(Name = "Date de l'évènement")]
        public string AjouterDate { get; set; }

        public List<EvenementViewModel> evenements { get; set; }
        public List<EvenementViewModel> invitations { get; set; }
        public List<EvenementViewModel> evenementsrecents { get; set; }

        public EvenementGlobalViewModel()
        {
            this.evenements = new List<EvenementViewModel>();
            this.invitations = new List<EvenementViewModel>();
            this.evenementsrecents = new List<EvenementViewModel>();
        }
    }
}

MeetHub/MeetHub/Controllers/EvenementController.cs
using MeetHub.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetHub.Controllers
{
    public class EvenementController : Controller
    {
        public ActionResult AfficherEvenements()
        {
            using (var context = new ApplicationDbContext())
            {
                var UserId = User.Identity.GetUserId();
                var ListeMesEvenements = context.Evenements
                    .Where(evenement => UserId == evenement.Createur.Id)
                    .Select(evenement => new
                    {
                        EvenementId = evenement.EvenementId,
                        Nom = evenement.Nom,
                        Lieu = evenement.Lieu,
                        Description = evenement.Description,
                        Date = evenement.Date,
                        Membres = evenement.Membres,
                        Createur = evenement.Createur
                    });

                var ListeParticipationEvenements = context.Evenements
                    .Where(evenement => evenement.Membres.Any(membre => membre.Id == UserId))
                    .Select(evenement => new
                    {
                        EvenementId = evenement.EvenementId,
                        Nom = evenement.Nom,
                        Lieu = evenement.Lieu,
                        Description = evenement.Description,
                        Date = evenement.Date,
                        Membres = evenement.Membres,
                        Createur = evenement.Createur
                    });

                var ListeEvenementsRecents = context.Evenements
                    .Where(evenement => !evenement.Membres.Any(membre => membre.Id == UserId))
                    .Select(evenement => new
                    {
                        EvenementId = evenement.EvenementId,
                        Nom = evenement.Nom,
                        Lieu = evenement.Lieu,
                        Description = evenement.Description,
                        Date = evenement.Date,
                        Membres = evenement.Membres,
                        Createur = evenement.Createur
                    });

                ViewBag.Message = "Evenements";
                var viewModel = new EvenementGlobalViewModel();
                foreach (var e in ListeMesEvenements)
                {
                    viewModel.evenements.Add(new EvenementViewModel
                    {
                        EvenementId = e.EvenementId,
                        Nom = e.Nom,
                        Lieu = e.Lieu,
                        Date = e.Date,
                        Description = e.Description,
                        NbMembres = e.Membres.Count().ToString(),
                        Createur = e.Createur
                    });
                }

                foreach (var e in ListeParticipationEvenements)
                {
                    viewModel.invitations.Add(new EvenementViewModel
                    {
                        EvenementId = e.EvenementId,
                        Nom = e.Nom,
                        Lieu = e.Lieu,
                        Date = e.Date,
                        Description = e.Description,
                        NbMembres = e.Membres.Count().ToString(),
                        Createur = e.Createur
                    });
                }

                foreach (var e in ListeEvenementsRecents)
                {
                    viewModel.evenementsrecents.Add(new EvenementViewModel
                    {
                        EvenementId = e.EvenementId,
                        Nom = e.Nom,
                        Lieu = e.Lieu,
                        Date = e.Date,
                        Description = e.Description,
                        NbMembres = e.Membres.Count().ToString(),
                        Createur = e.Createur
                    });
                }

                return View(viewModel);
            }
        }

        // POST: /Groupe/AjouterGroupe
        [HttpPost]
        [AllowAnonymous]
        public ActionResult AjouterEvenement(EvenementGlobalViewModel model)
        {
            using (var context = new ApplicationDbContext())
            {
                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);
                var evenement = new Evenement(model.AjouterNom, model.AjouterLieu, model.AjouterDescription, model.AjouterDate, Createur);
                evenement.Membres.Add(Createur);
                context.Evenements.Add(evenement);
                context.SaveChanges();
                return RedirectToAction("AfficherEvenements");
            }
        }

        public ActionResult SupprimerEvenement(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                var evenement = context.Evenements
                   .FirstOrDefault(e => Id == e.EvenementId);
                context.Evenements.Remove(evenement);
                context.SaveChanges();
                return RedirectToAction("AfficherEvenements");
            }
        }

        public ActionResult RejoindreEvenement(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                var evenement = context.Evenements
                    .Include("Membres")
                   .FirstOrDefault(e => Id == e.EvenementId);
                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);

                evenement.Membres.Add(Createur);
                context.SaveChanges();
                return RedirectToAction("AfficherEvenements");
            }
        }

        public ActionResult AnnulerEvenement(int Id)
        {
            using (var context = new ApplicationDbContext())
            {
                var evenement = context.Evenements
                    .Include("Membres")
                    .FirstOrDefault(e => Id == e.EvenementId);

                var UserId = User.Identity.GetUserId();
                var Createur = context.Users
                   .FirstOrDefault(user => UserId == user.Id);

                evenement.Membres.Remove(Createur);
                context.SaveChanges();
                return RedirectToAction("AfficherEvenements");
            }
        }
    }
}

MeetHub/MeetHub/Views/Evenement/AfficherEvenements.cshtml
@model MeetHub.Models.EvenementGlobalViewModel
@{
    ViewBag.Title = "Evenements";
}
<hr />
<div class="col-sm-12 container ">
    <div class="submain col-sm-6 col-sm-offset-3">
        @using (Html.BeginForm("AjouterEvenement", "Evenement", FormMethod.Post, new { @class = "ui form", role = "form" }))
        {
            <h4>Ajouter un nouvel évènement</h4>
            <hr />
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterNom, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextBoxFor(m => m.AjouterNom)
                </div>
            </div>
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterLieu, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextBoxFor(m => m.AjouterLieu)
                </div>
            </div>
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterDescription, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextAreaFor(m => m.AjouterDescription)
                </div>
            </div>
            <div class="field">
                <div class="ui labeled input">
                    @Html.LabelFor(m => m.AjouterDate, new { @class = "col-sm-3 col-xs-3 ui label" })
                    @Html.TextBoxFor(m => m.AjouterDate)
                </div>
            </div>
            <div class="field">
                <div class="text-center">
                    <input type="submit" class="ui button waves-effect waves-green" value="Ajouter" />
                </div>
            </div>
        }
    </div>
</div>
<hr />
<div class="col-sm-12 container">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200"> Mes Evenements </h4>
    <div class="row">
        @foreach (var evenement in Model.evenements)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big">@evenement.Nom</a>
                    <p>Adresse: @evenement.Date</p>
                    <p>Lieu: @evenement.Lieu</p>
                    <p>@evenement.NbMembres membre(s) y participe(nt)</p>
                    <p> Organisé(e) par: @evenement.Createur.Email</p>
                    <center>
                        <div class="ui buttons">
                            <button class="ui positive button">Modifier</button>
                            <div class="or" data-text="ou"></div>
                            @Html.ActionLink("SUPPRIMER", "SupprimerEvenement", new { Id = @evenement.EvenementId }, new { @class = "ui negative button" })
                        </div>
                    </center>
                </div>
            </div>
        }
    </div>
</div>
<hr>
<div class="col-sm-12 container">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200"> Participation aux evenements </h4>
    <div class="row">
        @foreach (var evenement in Model.invitations)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big">@evenement.Nom</a>
                    <p>Adresse: @evenement.Date</p>
                    <p>Lieu: @evenement.Lieu</p>
                    <p>@evenement.NbMembres membre(s) y participe(nt)</p>
                    <p> Organisé(e) par: @evenement.Createur.Email</p>
                    <center>
                        @Html.ActionLink("ANNULER PARTICIPATION", "AnnulerEvenement", new { Id = @evenement.EvenementId }, new { @class = "ui red button" })
                    </center>
                </div>
            </div>
        }
    </div>
</div>
<hr>
<div class="col-sm-12 container">
    <h4 class="animated text-muted" data-animation="fadeInUp" data-animation-delay="200"> Evenements ajoutés récemment </h4>
    <div class="row">
        @foreach (var evenement in Model.evenementsrecents)
        {
            <div class='col-sm-4 animated' data-animation="fadeInUp" data-animation-delay="200">
                <div class="ui raised segment">
                    <a class="ui teal ribbon label big">@evenement.Nom</a>
                    <p>Adresse: @evenement.Date</p>
                    <p>Lieu: @evenement.Lieu</p>
                    <p>@evenement.NbMembres membre(s) y participe(nt)</p>
                    <p> Organisé(e) par: @evenement.Createur.Email</p>
                    <center>
                        @Html.ActionLink("REJOINDRE", "RejoindreEvenement", new { Id = @evenement.EvenementId }, new { @class = "ui blue button" })
                    </center>
                </div>
            </div>
        }
    </div>
    <hr />
</div>